package pe.learnit.eticket;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pe.learnit.eticket.be.Producto;
import pe.learnit.eticket.bl.ProductoBL;

/**
 *
 * 
 */
public class FrmManProducto extends javax.swing.JDialog {
    private ProductoBL _productoBL; 
    private boolean esNuevo;
    /**
     * Creates new form FrmManProducto
     */
    public  FrmManProducto(java.awt.Frame parent, boolean modal,String codigo) {
        super(parent, modal);
        initComponents();
        _productoBL = new ProductoBL();
        
            if (codigo.isEmpty())
            esNuevo = true; //invocado desde opcion NUEVO
        else
            esNuevo = false; //invocado desde opcion EDITAR
            
            
        
        llenarFormulario(codigo);
        
        
    }

     private void llenarFormulario(String codigo){
        if (!codigo.isEmpty()){
            try {
                Producto producto = _productoBL.getByCodigo(codigo);
                
                if (producto != null)
                {
                    txtCodigo.setText(producto.getCodigo());
                    txtDescripcion.setText(producto.getDescripcion());
                    txtPrecioUnitario.setText(String.valueOf(producto.getPrecioUnitario()));
                    txtCodigo.setEnabled(false);
                }else{
                    JOptionPane.showMessageDialog(this, "Producto no existe.", "Error", JOptionPane.ERROR_MESSAGE);
                    dispose();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    
    /*
    private void llenarFormulario(String codigo){
    
        
         if (!codigo.isEmpty()){
             Producto producto;
             try {
                 producto = _productoBL.getByCodigo(codigo);
             } catch (SQLException ex) {
                 Logger.getLogger(FrmManProducto.class.getName()).log(Level.SEVERE, null, ex);
             }
             if (producto != null)
             {
                 txtCodigo.setText(producto.getCodigo());
                 txtDescripcion.setText(producto.getDescripcion());
                 txtPrecioUnitario.setText(String.valueOf(producto.getPrecioUnitario()));
                 txtCodigo.setEnabled(false);
             }else{
                 JOptionPane.showMessageDialog(this, "Producto no existe.", "Error", JOptionPane.ERROR_MESSAGE);
                 dispose();
             }
        }
       
        
    }   */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        txtDescripcion = new java.awt.TextField();
        txtPrecioUnitario = new java.awt.TextField();
        tnAceptar = new java.awt.Button();
        btnCancelar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código:");

        txtCodigo.setName(""); // NOI18N

        label1.setText("Descripción:");

        label2.setText("Precio Unitario:");

        tnAceptar.setLabel("Aceptar");
        tnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setLabel("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(tnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(20, 20, 20)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
     this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnAceptarActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_tnAceptarActionPerformed
    private void guardar(){
  
        try {
            
                if (esValidoParaGuardar()) {
                       Producto producto = new Producto();
                       producto.setCodigo(txtCodigo.getText().trim());
                       producto.setDescripcion(txtDescripcion.getText().trim());
                       producto.setPrecioUnitario(Double.valueOf(txtPrecioUnitario.getText().trim()));
                       producto.setRowStatus("1");
                      
                           if (esNuevo)
                    _productoBL.insertar(producto);
                else
                    _productoBL.modificar(producto);
                
                JOptionPane.showMessageDialog(this, "Operación ejecutada con éxito.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                
                this.dispose();
                       
                       /* algo huele mal -.-
                       _productoBL.insertar(producto);
                       JOptionPane.showMessageDialog(this, "Operación ejecutada con éxito","Aviso",JOptionPane.INFORMATION_MESSAGE);
                       this.dispose();
                    */
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(FrmManProducto.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            
        }
    }
    
    
    
    private boolean esValidoParaGuardar() throws SQLException{
        
        if (txtCodigo.getText().trim().equals("")) {
            JOptionPane.showMessageDialog( this,"Llene el Campo Codigo","PELIGRO",JOptionPane.ERROR_MESSAGE );
            return false;
        }
        if (txtDescripcion.getText().trim().equals("")) {
            JOptionPane.showMessageDialog( this,"Llene el Campo Descripcion","PELIGRO",JOptionPane.ERROR_MESSAGE );
            return false;
        }
        if (txtPrecioUnitario.getText().trim().equals("")) {
            JOptionPane.showMessageDialog( this,"Llene el Campo Precio ","PELIGRO",JOptionPane.ERROR_MESSAGE );
            return false;
        }else{
            Double n =Double.valueOf(txtPrecioUnitario.getText());
            if (n<=0) {
                
            JOptionPane.showMessageDialog( this,"Precio debe ser mayor a cero","PELIGRO",JOptionPane.ERROR_MESSAGE );
            return false;
            }
        }
         if (esNuevo && _productoBL.existe(txtCodigo.getText().trim())){
            JOptionPane.showMessageDialog(this, "Código ya utilizado.", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
       /* 
        ProductoBL productoBL=new ProductoBL();
        if (productoBL.existe(txtCodigo.getText().trim())) {
          JOptionPane.showMessageDialog( this,"Perroro","PELIGRO",JOptionPane.ERROR_MESSAGE );
            return false;   
        }
        */
      
        return true;
    }
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnCancelar;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Button tnAceptar;
    private java.awt.TextField txtCodigo;
    private java.awt.TextField txtDescripcion;
    private java.awt.TextField txtPrecioUnitario;
    // End of variables declaration//GEN-END:variables
}
